name: Bug Report
description: File a bug report
title: '<title>'
labels: ['bug']
assignees:
  - pablo-abc
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: dropdown
    id: packages
    attributes:
      label: Which package/s are you using?
      description: |
        Select the Felte packages you're using in your project.

        Note: `@felte/core` and `@felte/common` are not meant to be used by consumers but package authors.
      multiple: true
      options:
        - felte (Svelte)
        - '@felte/reporter-svelte'
        - '@felte/solid (SolidJS)'
        - '@felte/reporter-solid'
        - '@felte/react (ReactJS)'
        - '@felte/reporter-react'
        - '@felte/preact (PreactJS)'
        - '@felte/reporter-preact'
        - '@felte/element (VanillaJS through custom elements)'
        - '@felte/reporter-element'
        - '@felte/vanilla (VanillaJS with `createForm` and `createField`)'
        - '@felte/validator-yup'
        - '@felte/validator-zod'
        - '@felte/validator-superstruct'
        - '@felte/validator-vest'
        - '@felte/reporter-tippy'
        - '@felte/reporter-dom'
        - '@felte/reporter-cvapi'
        - '@felte/core'
        - '@felte/common'
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please complete the following information.

        Example:
          - OS: [e.g. iOS]
          - Browser: [e.g. chrome, safari]
          - Version: [e.g. felte@1.0.0, @felte/reporter-svelte@1.0.0]
      value: |
        - OS:
        - Browser:
        - Version:
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: To reproduce
      description: |
        Steps to reproduce the behaviour.

        Example:
          1. Go to '...'
          2. Click on '....'
          3. Scroll down to '....'
          4. See error
    validations:
      required: false
  - type: input
    id: example
    attributes:
      label: Small reproduction example
      description: If possible, a small reproduction would help us solve this quicker!
      placeholder: https://codesandbox.io/s/...
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: |
        If applicable, add screenshots to help explain your problem.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about your problem here.
    validations:
      required: false
